// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestMailer.Infrastructure.Persistence;

#nullable disable

namespace TestMailer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MailingDbContext))]
    [Migration("20230704131734_CommentsForColumns")]
    partial class CommentsForColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestMailer.Domain.Mailing.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body")
                        .HasComment("Тело письма");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Дата создания и отправки");

                    b.Property<string>("FailedMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failed_message")
                        .HasComment("Описание ошибки при отправке (если есть)");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result")
                        .HasComment("Результат отправки");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("subject")
                        .HasComment("Тема письма");

                    b.Property<List<string>>("_recipients")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("recipients")
                        .HasComment("Получатели");

                    b.HasKey("Id")
                        .HasName("pk_email");

                    b.HasIndex("Subject")
                        .HasDatabaseName("ix_email_subject");

                    b.ToTable("email", "Mailing");
                });
#pragma warning restore 612, 618
        }
    }
}
